name: 'de_platform'
version: '1.0.0'
config-version: 2

profile: 'de_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  de_platform:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
