-- ==========================================
-- Project 2: Social Media Sentiment
-- Snowflake Setup & Infrastructure Script
-- ==========================================

-- 1. Create the Security Role
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS SENTIMENT_APP_ROLE;

-- 2. Create the Compute Warehouse
CREATE WAREHOUSE IF NOT EXISTS STREAMING_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE STREAMING_WH TO ROLE SENTIMENT_APP_ROLE;

-- 3. Create the Database and Schema
CREATE DATABASE IF NOT EXISTS SOCIAL_MEDIA_DB;
GRANT USAGE ON DATABASE SOCIAL_MEDIA_DB TO ROLE SENTIMENT_APP_ROLE;

USE DATABASE SOCIAL_MEDIA_DB;
CREATE SCHEMA IF NOT EXISTS RAW;
GRANT USAGE ON SCHEMA RAW TO ROLE SENTIMENT_APP_ROLE;
GRANT CREATE TABLE ON SCHEMA RAW TO ROLE SENTIMENT_APP_ROLE;

-- 4. Create the Service User
CREATE USER IF NOT EXISTS STREAMING_USER
    PASSWORD = 'your_secure_password_here'  -- pragma: allowlist secret
    DEFAULT_ROLE = SENTIMENT_APP_ROLE
    DEFAULT_WAREHOUSE = STREAMING_WH
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SENTIMENT_APP_ROLE TO USER STREAMING_USER;

-- 5. Create the Destination Table
-- This table receives the final output from our PySpark sentiment processor
USE ROLE SENTIMENT_APP_ROLE;
USE WAREHOUSE STREAMING_WH;
USE DATABASE SOCIAL_MEDIA_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SENTIMENT_RESULTS (
    USER_ID VARCHAR,
    TWEET_TEXT VARCHAR,
    LOCATION VARCHAR,
    TWEET_TIMESTAMP TIMESTAMP,
    SENTIMENT_SCORE FLOAT,
    PROCESSED_AT TIMESTAMP
);

-- Grant privileges so the app role can insert into the table
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SENTIMENT_RESULTS TO ROLE SENTIMENT_APP_ROLE;
